version: '3.9'
services:
  postgres:
    image: postgres:15  # Corrected from 'images' to 'image'
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: online-shopping
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:  
